### ISSUE TITLE
this sucks for one u didnt even put all the stuff u would have to change around and the only thing that works is the brand!

### ISSUE THREAD

**Issue by BenS12362** [vanflux/cursors-io-bot#1]
now also make the proxys work it sucks

**Comment by vanflux** [comment]
The "LevelUnlocker" has bugs, however, when I use my SOCKS proxies, 99.9% of the time it works without errors. I forgot to mention it, but the supported proxies are of the 'SOCKS' type, not 'HTTP'. Maybe you are testing something different. What things did i forget to put in the bot?

**Comment by vanflux** [comment]
I have tested "Level Unlocker" now, with proxies, everything is working normally. Try with other proxies, try using tor.
Don't forget, the proxies are not in the repository, you have to configure the agentManager with your proxies.

**Comment by vanflux** [comment]
Closing issue.
